sudo: required

services:
    - docker

script:
    # Compile all sources
    - docker run --rm -v $PWD/src:/data -w /data nguillaumin/vasm make
    # Generate HTML from AsciiDoc
    - docker run --rm -v $PWD:/documents asciidoctor/docker-asciidoctor bash -c "gem install asciidoctor-multipage && asciidoctor -a source-highlighter=rouge -a docinfo1 -r asciidoctor-multipage -b multipage_html5 index.adoc"
    # Generate ePub from AsciiDoc
    - docker run --rm -v $PWD:/documents asciidoctor/docker-asciidoctor bash -c "asciidoctor-epub3 -a source-highlighter=rouge epub.adoc -o perihelion-m68k-tutorials.epub"
    # Remove files unnecessary on GitHub pages
    - rm -f .travis.yml
    - rm -f .gitignore
    - rm -f *.adoc
    # Cleanup compiled files - Sources must be preserved as they are linked to from the tutorials
    - docker run --rm -v $PWD/src:/data -w /data nguillaumin/vasm make clean
    # Disable Jekyll processing as it ignores files starting with an underscore,
    # which AsciiDoctor generates
    - touch .nojekyll

deploy:
    provider: pages
    skip_cleanup: true
    github_token: $GITHUB_TOKEN
