= The Atari ST MC68000 Assembly Language Tutorials
:source-language: m68k
originally by perihelion of poSTmortem

image:https://travis-ci.org/nguillaumin/perihelion-m68k-tutorials.svg?branch=master["Build Status", link="https://travis-ci.org/nguillaumin/perihelion-m68k-tutorials"]

This repository contains the text of the tutorials written by perihelion to
learn Motorola 68000 development on the Atari ST.

The original tutorials can be found on the http://atari-forum.com/viewtopic.php?f=68&t=4330[Atari Forums]

The texts have been converted from the single-page PDF into AsciiDoc, then
manually corrected where necessary. The assembly sources have been reformatted
and split out in separate files. Apart from minor edits, the text and sources
are identical to the originals.

The main motivation to do so were:

* Have an alternative format to the original PDF
* Ability to read the tutorials in a browser, in a (hopefully) pleasant font
* Make it it easier to read on mobile devices / small screens
* Setup a cross-compilation system for development on a modern machine host
to compile the example sources (see link:src/[src/])
* Produce an e-book (ePub) for e-readers
* Have access to the raw text so that it can be shared and improved by other
contributors (possibly contribute entirely new tutorials?)

== Assembling the examples

The example sources are in link:src/[src/]. They can be cross-assembled using
http://sun.hasenbraten.de/vasm/[vasm]. A link:src/Makefile[Makefile] is provided
to assemble all examples, as well as building a `.st` image with all the
examples and running it with https://hatari.tuxfamily.org/[Hatari].

See the content of the Makefile for details.

== To do

A few issues remain:

* I grabbed some images such as the different sprite operations (AND, OR, etc.)
from the original PDF. It would be better to write the programs that generated
these images and grab a screenshot instead.
* The tabs on the code example and source files are a bit too wide, making them
hard to read on small screens. They should be reduced.
* Update the source code to be compatible with Devpac so that it can be compiled
on an Atari (remove spaces after commas).
